-- 添加 article 表缺少的字段
ALTER TABLE article ADD COLUMN IF NOT EXISTS `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序权重';
ALTER TABLE article ADD COLUMN IF NOT EXISTS `ai_summary` TEXT DEFAULT NULL COMMENT 'AI生成摘要';
ALTER TABLE article ADD COLUMN IF NOT EXISTS `knowledge_points` VARCHAR(512) DEFAULT NULL COMMENT 'AI拆解知识点';
ALTER TABLE article ADD COLUMN IF NOT EXISTS `sync_bailian` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否同步到百炼';
ALTER TABLE article ADD COLUMN IF NOT EXISTS `bailian_doc_id` VARCHAR(128) DEFAULT NULL COMMENT '百炼文档标识';
ALTER TABLE article ADD COLUMN IF NOT EXISTS `content_hash` VARCHAR(64) DEFAULT NULL COMMENT '内容哈希值';
ALTER TABLE article ADD COLUMN IF NOT EXISTS `file_path` VARCHAR(255) DEFAULT NULL COMMENT '文件路径';
ALTER TABLE article ADD COLUMN IF NOT EXISTS `version` INT NOT NULL DEFAULT 1 COMMENT '版本号';
